### ISSUE TITLE
What's the newest documentation version?

### ISSUE THREAD

**Issue by sixtyfive** [svn2github/transistortester#4]
Looking at transistortester/Doku/trunk/pdftex/german, that folder has last been updated 5 months ago, but the PDF file inside of it (ttester.pdf) is 3 years old. I tried compiling from scratch and failed miserably:

```
set timefmt z "%d/%m/%y,%H:%M"
            ^
"../GNU/Cap_FC_data.gnu", line 21: unexpected or unrecognized token
```

Would it be possible for you to do the recompile and upload the latest documentation version?

**Comment by ValZapod** [comment]
@sixtyfive Latest version is 1.13k
[ttester_en.pdf](https://github.com/svn2github/transistortester/files/3532932/ttester_en.pdf)
http://www.avrtester.tode.cz/upload/ttester_en.pdf

**Comment by sixtyfive** [comment]
Thanks a bunch, @ValZapod! :)
